"""Generate baseline vs hardened comparison report from audit JSONL."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from agent_security_lab.observability.audit import read_tool_audits

ATTACK_MARKERS = {
    "poisoning": ["poison", "summarize_notes", "sensitive", "IMPORTANT"],
    "rug_pull": ["schema_pin", "rug", "pin_mismatch", "description_hash_mismatch"],
    "shadowing": ["shadow", "name_conflict", "shadowing"],
}


def _classify_event(row: dict[str, Any]) -> str:
    blob = " ".join(
        [
            str(row.get("event", "")),
            str(row.get("tool_name", "")),
            " ".join(row.get("policy", {}).get("reasons") or []),
            str(row.get("extra", {})),
        ]
    ).lower()
    for name, keys in ATTACK_MARKERS.items():
        if any(k.lower() in blob for k in keys):
            return name
    return "other"


def build_comparison_report(
    baseline_audit: Path,
    hardened_audit: Path,
    *,
    output: Path | None = None,
) -> str:
    base_rows = read_tool_audits(limit=10_000, path=baseline_audit)
    hard_rows = read_tool_audits(limit=10_000, path=hardened_audit)

    def stats(rows: list[dict[str, Any]]) -> dict[str, Any]:
        by = defaultdict(lambda: {"allow": 0, "deny": 0, "require_approval": 0, "total": 0})
        for r in rows:
            cat = _classify_event(r)
            by[cat]["total"] += 1
            verdict = (r.get("policy") or {}).get("verdict") or r.get("event", "")
            if "deny" in str(verdict) or str(r.get("event", "")).endswith("denied"):
                by[cat]["deny"] += 1
            elif "require_approval" in str(verdict) or "approval" in str(r.get("event", "")):
                by[cat]["require_approval"] += 1
            elif "allow" in str(verdict) or str(r.get("event", "")).endswith("allowed"):
                by[cat]["allow"] += 1
        return dict(by)

    bstat = stats(base_rows)
    hstat = stats(hard_rows)

    lines = [
        "# Baseline vs Hardened — Attack Outcome Report",
        "",
        "Generated by `agent_security_lab.observability.report`.",
        "",
        "## Summary table",
        "",
        "| Scenario | Baseline allows | Baseline denies/approval | Hardened allows | Hardened denies/approval | Primary block stage |",
        "|---|---:|---:|---:|---:|---|",
    ]

    scenarios = ["poisoning", "rug_pull", "shadowing", "other"]
    block_hints = {
        "poisoning": "rule_of_two / sigma / description_guard",
        "rug_pull": "schema_pin",
        "shadowing": "tool_router / description_guard",
        "other": "varies",
    }
    for s in scenarios:
        bs = bstat.get(s, {})
        hs = hstat.get(s, {})
        lines.append(
            f"| {s} | {bs.get('allow', 0)} | "
            f"{bs.get('deny', 0) + bs.get('require_approval', 0)} | "
            f"{hs.get('allow', 0)} | "
            f"{hs.get('deny', 0) + hs.get('require_approval', 0)} | "
            f"{block_hints[s]} |"
        )

    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Baseline audit events: **{len(base_rows)}** (`{baseline_audit}`)",
            f"- Hardened audit events: **{len(hard_rows)}** (`{hardened_audit}`)",
            "",
            "## Interpretation",
            "",
            "- **Baseline** profile records policy context but does not enforce Rule of Two,",
            "  schema pins, or approval for state changes (sandbox path limits still apply",
            "  inside servers).",
            "- **Hardened** profile requires approval when ≥2 Lethal Trifecta dimensions are",
            "  active, denies schema pin mismatches, and gates `send_email` behind single-use tokens.",
            "",
            "## Hardened deny / approval samples",
            "",
        ]
    )

    samples = [
        r
        for r in hard_rows
        if "deny" in str((r.get("policy") or {}).get("verdict", ""))
        or "require_approval" in str((r.get("policy") or {}).get("verdict", ""))
        or str(r.get("event", "")).endswith("denied")
    ][:15]
    if not samples:
        lines.append("_No deny/approval samples found in hardened audit._")
    for r in samples:
        lines.append(
            f"- `{r.get('ts')}` **{r.get('event')}** tool=`{r.get('tool_name')}` "
            f"reasons={((r.get('policy') or {}).get('reasons'))}"
        )

    lines.append("")
    text = "\n".join(lines)
    if output is not None:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text, encoding="utf-8")
    return text
